---
# Secret for Azure Service Bus credentials
apiVersion: v1
kind: Secret
metadata:
  name: azure-sb-secret
  namespace: default
  labels:
    app: bestbuy
  annotations:
    description: "Contains Azure Service Bus connection strings."
type: Opaque
data:
  SB_SEND_CONNECTION_STRING: "RW5kcG9pbnQ9c2I6Ly9iZXN0YnV5LXNiLTEyMzQ1LnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9c2VuZC1wb2xpY3k7U2hhcmVkQWNjZXNzS2V5PWxCV2huV2dHSDhkNkhEZmg2ZFIycUh1QisemVXV2J1VnIrQVNiQVhMU1Z3PTtFbnRpdHlQYXRoPW9yZGVycw=="
  SB_LISTEN_CONNECTION_STRING: "RW5kcG9pbnQ9c2I6Ly9iZXN0YnV5LXNiLTEyMzQ1LnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9bGlzdGVuLXBvbGljeTtTaGFyZWRBY2Nlc3NLZXk9VVhPVUtabThuYVpuRHFMTW44UUlZSEUvZitoc1c2WGcrQVNiT2ZGK0h3PTtFbnRpdHlQYXRoPW9yZGVycw=="

---
# Secret for OpenAI API key
apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
  namespace: default
  labels:
    app: bestbuy
  annotations:
    description: "Contains OpenAI API Key"
type: Opaque
data:
  OPENAI_API_KEY: "Base64-encoded-API-KEY"

---
# Deployment and Service for MongoDB (StatefulSet)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.2
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
  type: ClusterIP

---
# Deployment and Service for Order Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ethan200530/order-service:v4
          ports:
            - containerPort: 3000
          env:
            - name: SERVICEBUS_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: azure-sb-secret
                  key: SB_SEND_CONNECTION
            - name: ORDER_QUEUE_NAME
              value: "orders"
            - name: FASTIFY_ADDRESS
              value: "0.0.0.0"
            - name: ORDER_QUEUE_URI
              value: "amqps://bestbuy-sb-12345.servicebus.windows.net"


---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: order-service

---
# Deployment and Service for Makeline Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
        - name: makeline-service
          image: ethan200530/makeline-service:v2
          ports:
            - containerPort: 3001
          env:
            - name: ORDER_QUEUE_URI
              value: "amqps://bestbuy-sb-12345.servicebus.windows.net"
            - name: ORDER_QUEUE_USERNAME
              value: "listen-policy"
            - name: ORDER_QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-sb-secret
                  key: SB_LISTEN_KEY
            - name: ORDER_QUEUE_NAME
              value: "orders"
            - name: ORDER_DB_URI
              value: "mongodb://mongodb:27017"
            - name: ORDER_DB_NAME
              value: "orderdb"
            - name: ORDER_DB_COLLECTION_NAME
              value: "orders"

---
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  selector:
    app: makeline-service





# Deployment and Service for Product Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ramymohamed/product-service-l8:latest
          ports:
            - containerPort: 3002
          env:
            - name: AI_SERVICE_URL
              value: "http://ai-service:5001/"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3002
      targetPort: 3002
  selector:
    app: product-service

---
# Deployment and Service for Store Front
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      containers:
        - name: store-front
          image: ethan200530/store-front:v3
          ports:
            - containerPort: 8080
          env:
            - name: VUE_APP_ORDER_SERVICE_URL
              value: "http://order-service:3000/"
            - name: VUE_APP_PRODUCT_SERVICE_URL
              value: "http://product-service:3002/"
---
apiVersion: v1
kind: Service
metadata:
  name: store-front
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: store-front
  type: NodePort

---
# Deployment for Store Admin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
        - name: store-admin
          image: ethan200530/store-admin:latest
          ports:
            - containerPort: 8081
          env:
            - name: VUE_APP_PRODUCT_SERVICE_URL
              value: "http://product-service:3002/"
            - name: VUE_APP_MAKELINE_SERVICE_URL
              value: "http://makeline-service:3001/"
            - name: AI_SERVICE_URL
              value: "http://ai-service:5001"

---

# ✅ 已修改：Service for Store Admin （使用 NodePort，端口 31880）
apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  type: NodePort
  selector:
    app: store-admin
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 31880

# Deployment and Service for AI Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: ramymohamed/ai-service-l8:latest
          ports:
            - containerPort: 5001
          env:
            - name: USE_AZURE_OPENAI
              value: "false"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api_key
            - name: OPENAI_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: org_id

---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5001
      targetPort: 5001
  selector:
    app: ai-service

